---
- hosts: Middleware
  become: yes
  tasks: 
    - name: install java8
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - openjdk-8-jdk
        - tomcat8 
        - tomcat8-docs 
        - tomcat8-admin 
        - tomcat8-examples
        - unzip
